name: Deploy

on:
  push:
    branches: [ "main" ] #whenever their is an push to main

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    # Authenticate with Google Cloud
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCLOUD_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Configure Docker to authenticate with Google Container Registry or Artifact Registry
    - name: Configure Docker to use Google Cloud
      run: gcloud auth configure-docker

    # Build the Docker image (specify the Dockerfile in the nest_app folder)
    - name: Build Docker image
      run: docker build -f nest_app/Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nest-app:${{ github.sha }} .
      working-directory: .

    # Push the Docker image to Google Container Registry or Artifact Registry
    - name: Push Docker image
      run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nestjs-cicd/nest-app:${{ github.sha }}


    # Deploy to GKE
    - name: Get GKE credentials
      run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}
    - name: Deploy to GKE
      run: |
        kubectl set image deployment/nest-app nest-app=gcr.io/${{ secrets.GCP_PROJECT_ID }}/nest-app:${{ github.sha }}