apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app  # Changed to lowercase with a dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app  # Changed to lowercase with a dash
  template:
    metadata:
      labels:
        app: nest-app  # Changed to lowercase with a dash
    spec:
      containers:
      - name: nest-app  # Changed to lowercase with a dash
        image: us-central1-docker.pkg.dev/adev-spark/nestjs-cicd/nest-app:latest
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
        resources:
          requests:
            memory: "512Mi"  # or "256Mi"
            cpu: "200m"      # adjust as necessary
          limits:
            memory: "512Mi"  # or "256Mi"
            cpu: "200m"      # adjust as necessary

---
apiVersion: v1
kind: Service
metadata:
  name: nest-app-service  # You can name it appropriately
spec:
  type: LoadBalancer  # This exposes the service externally with a cloud load balancer
  selector:
    app: nest-app  # Matches the app label from the Deployment
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 3000  # Port where the NestJS app is running inside the container