apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app  # Changed to lowercase with a dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app  # Changed to lowercase with a dash
  template:
    metadata:
      labels:
        app: nest-app  # Changed to lowercase with a dash
    spec:
      containers:
      - name: nest-app  # Changed to lowercase with a dash
        image: us-central1-docker.pkg.dev/adev-spark/nestjs-cicd/nest-app:latest
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
        resources:
          requests:
            memory: "512Mi"  # or "256Mi"
            cpu: "250m"      # adjust as necessary
          limits:
            memory: "512Mi"  # or "256Mi"
            cpu: "500m"      # adjust as necessary
